name: Google Test CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Run Test Suite
      - uses: actions/checkout@v3
      - run: mkdir ${{github.workspace}}/tests/build && cd ${{github.workspace}}/tests/build && cmake .. && cmake --build . && ./Google_Tests_run
